name: docker

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        name:
          - dachub_auth
        include:
          - name: dachub_auth
            FOLDER: dachub_auth
            PLATFORM: "linux/amd64" #,linux/arm64"
            IMAGE: dachub_auth

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # create metadata for image
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            hub.ncsa.illinois.edu/dachub/${{ matrix.IMAGE }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to NCSA Hub
        uses: docker/login-action@v3
        with:
          registry: hub.ncsa.illinois.edu
          name: dachub/
          username: ${{ secrets.NCSA_HUB_USERNAME }}
          password: ${{ secrets.NCSA_HUB_PASSWORD }}

      # build and push
      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.FOLDER }}
          push: true
          platforms: ${{ matrix.PLATFORM }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
